### ISSUE TITLE
#fmt: off #fmt: on breaks formatting when applied only to decorators

### ISSUE THREAD

**Issue by mnowotnik** [python/black#913] opened 2019-06-26 21:07 UTC
Formatting stops working after enclosing only decorators in an #fmt block.
[link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACxAHldAD2IimZxl1N_Wk6rl6o73hy4EdfLRZlHwkEyQnGJEvbrVqxpcyPoxGLK4QHtg1NSD_pTEKTTf9zgdiJ33nEuraZnZwwo_l6ttpIwoF3UgZ6J5RkLCSsKDnojwR7BOq49XeFjYBNWIIw_ecxH4igMVsPhRnA9zzWqhwAAAAAAgNkSB4aTHJMAAZUBsgEAALuWJwWxxGf7AgAAAAAEWVo=)

**Comment by zsol** [comment] 2019-06-28 22:39
Duplicate of #560

**Closed by zsol** 2019-06-28 22:39 UTC
