### ISSUE TITLE
Mypy fails after running black on my codebase

### ISSUE THREAD

**Issue by ltworf** [python/black#873] opened 2019-05-27 09:31 UTC
This:

```python3
parent_parser = argparse.ArgumentParser(**_arg_parser_kwargs(root_class))  # type: ignore
```

Became this:

```python3
parent_parser = argparse.ArgumentParser(
    **_arg_parser_kwargs(root_class)
)  # type: ignore
```

So now mypy complains because i'm ignoring a`)` and I shouldn't be doing that, and the actual thing I was ignoring is no longer ignored, so that fails too.

**Comment by striglia** [comment] 2019-05-28 23:15
I recently experienced the same behavior with a flake8 `noqa` tag from roughly:
```
from foo.bar.baz import a_long_enough_thing_to_trigger_linebreaks  # noqa
```
to this version, which flake8 (similarly to mypy in @ltworf's example) fails to noqa entirely.
```
from foo.bar.baz import (
    a_long_enough_thing_to_trigger_linebreaks,
)  # noqa
```

I could totally hear an argument this behavior is a little finicky from mypy/flake8, but the fact that they both exhibit the same behavior is telling.

**Comment by zsol** [comment] 2019-05-29 07:25
duplicate of #195

**Closed by zsol** 2019-05-29 07:25 UTC
