### ISSUE TITLE
splitting of chain assignment statements

### ISSUE THREAD

**Issue by akhmerov** [python/black#919] opened 2019-07-04 12:27 UTC
Long expressions of form `a = b = c` are oddly formatted:

Original:
```python
hamiltonian = hamiltonian_submatrix = modes = selfenergy = \
inter_cell_hopping = cell_hamiltonian = precalculated = \
_require_system
```
Black:
```python
hamiltonian = (
    hamiltonian_submatrix
) = (
    modes
) = (
    selfenergy
) = (
    inter_cell_hopping
) = cell_hamiltonian = precalculated = _require_system
```

Operating system: Ubuntu
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by zsol** [comment] 2019-07-05 07:23
Duplicate of #434.

**Closed by zsol** 2019-07-05 07:23 UTC

**Comment by akhmerov** [comment] 2019-07-05 07:38
Sorry, I overlooked that one.
