### ISSUE TITLE
Unable to format ignored decorator in class

### ISSUE THREAD

**Issue by USSRLivesOn** [python/black#718] opened 2019-02-19 17:24 UTC
Operating system: MacOS 10.14.3
Python version: 3.6.6
*Black* version: 18.9b0
Does also happen on master: Yes

Input:
```python
class MyClass:

    # fmt: off
    @mydecorator
    # fmt: on
    def test_decorated(self):
        pass

foo = 'foo'
```

Result:
`
 INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: /var/folders/d6/wn1mqq2j05n50jjvrtk94scr0000gn/T/blk_xq234z_q.log
`

This is the minimal reproducing case I could reduce it to. Not exactly sure where the issue is, but I figured it would be helpful to file. Thanks for working on Black!

**Comment by zsol** [comment] 2019-02-20 08:18
Looks like the indentation is messed up after `# fmt: on` in this case.

input:
```
class X:
  # fmt: off
  @lol
  # fmt: on
  def f():
    pass
f = 'f'
```

output:
```
class X:
    # fmt: off
  @lol
  # fmt: on
  def f():
    pass
    f = "f"
```

**Comment by pawelad** [comment] 2019-03-09 02:19
Just encountered the same problem when trying to tell `black` not to format Click decorators but do format the rest of the file. This doesn't work:

```python
# fmt: off
@click.command()
@click.option(
    "--interactive", "-i",
    is_flag=True, default=False, show_default=True,
    help="Open the browser.",
)
# fmt: on
def foo(interactive):
	# Some ugly code here
```

**Comment by pawelad** [comment] 2019-03-09 02:39
Actually, mine seems to be a duplicate of https://github.com/ambv/black/issues/560 - not sure if they're the same / related. Sorry for posting in the wrong thread if they're not.

**Comment by zsol** [comment] 2019-06-28 22:39
Yep, dupe of #560

**Closed by zsol** 2019-06-28 22:39 UTC
Labels: bug, invalid code
