### ISSUE TITLE
unpack to varialbes more than line-length chars can be flake8 uncompatible

### ISSUE THREAD

**Issue by tbicr** [python/black#784] opened 2019-03-27 19:28 UTC
given:
```
test_1234567890_1, test_1234567890_2, test_1234567890_3, test_1234567890_4, test_1234567890_5, \
    test_1234567890_6, test_1234567890_7 = range(7)
```

run:
`black --safe -S -l 100 file.py`

got:
```
test_1234567890_1, test_1234567890_2, test_1234567890_3, test_1234567890_4, test_1234567890_5, test_1234567890_6, test_1234567890_7 = range(
    7
)
```

expect:
```
(
    test_1234567890_1,
    test_1234567890_2,
    test_1234567890_3,
    test_1234567890_4,
    test_1234567890_5,
    test_1234567890_6,
    test_1234567890_7,
) = range(7)
```

Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04.6 LTS
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

**Comment by JelleZijlstra** [comment] 2019-05-06 18:28
Duplicate of #656.

**Closed by JelleZijlstra** 2019-05-06 18:28 UTC
Labels: design
