### ISSUE TITLE
Black should remove unnecessary outer parentheses around function arguments

### ISSUE THREAD

**Issue by jdufresne** [python/black#548] opened 2018-10-02 20:33 UTC
Operating system: **Fedora release 27**
Python version: **Python 3.6.6**
*Black* version: **18.9b0**
Does also happen on master: **Yes**

Input:

```py
print((1))
```

Expected change:

```py
print(1)
```

Actual: file left unchanged

**Comment by rooterkyberian** [comment] 2018-10-04 15:10
`print(((1)))` will also be unchanged where we expected it to be equal to `print(1)`

Something that is likely another issue, but similar:
```
f = lambda a: (1)
g = lambda a: ((1))
```
will also be left unchanged

tested with 
Python version: Python 3.7.0
Black version: 18.9b0

**Comment by sr105** [comment] 2019-04-25 16:59
Duplicate of #445

**Comment by JelleZijlstra** [comment] 2019-05-05 18:39
Don't think this is quite a dupe.

**Comment by sr105** [comment] 2019-05-06 18:11
Both involve black removing unnecessary tuple parentheses. The code to fix one will likely fix the other.

**Closed** 2019-05-16 04:11 UTC
Labels: design
